# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-07-20 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(db_index=True, verbose_name='\u65e5\u671f')),
                ('home', models.CharField(db_index=True, max_length=254)),
                ('away', models.CharField(db_index=True, max_length=254)),
                ('winner', models.CharField(db_index=True, max_length=254)),
                ('home_casualties', models.CharField(max_length=8192)),
                ('away_casualties', models.CharField(max_length=8192)),
                ('uptime', models.DateTimeField(auto_now=True, verbose_name='\u6570\u636e\u66f4\u65b0\u65f6\u95f4')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BattleProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battle_id', models.IntegerField(db_index=True, default=0)),
                ('round', models.IntegerField(default=0)),
                ('belong', models.CharField(max_length=32)),
                ('unit', models.CharField(max_length=64)),
                ('target', models.CharField(max_length=64)),
                ('move', models.CharField(max_length=64)),
                ('result', models.CharField(max_length=64)),
                ('uptime', models.DateTimeField(auto_now=True, verbose_name='\u6570\u636e\u66f4\u65b0\u65f6\u95f4')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
