# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-07-20 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='away_casualties',
            field=models.CharField(blank=True, max_length=8192, null=True),
        ),
        migrations.AlterField(
            model_name='battle',
            name='home_casualties',
            field=models.CharField(blank=True, max_length=8192, null=True),
        ),
        migrations.AlterField(
            model_name='battle',
            name='winner',
            field=models.CharField(blank=True, db_index=True, max_length=254, null=True),
        ),
    ]
